# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

matrix:
  include:
    - python: 3.8
      env: TOXENV=quality
    - python: 3.8
      env: TOXENV=docs

cache:
  - pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov

# Set token via "travis encrypt --add deploy.password"; for details, see
# https://docs.travis-ci.com/user/deployment/pypi
deploy:
  provider: pypi
  user: "__token__"
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: '$TOXENV = quality'
